FROM nvidia/cuda:11.7.1-devel-ubuntu20.04

RUN apt update && \
    DEBIAN_FRONTEND=noninteractive \
    apt install --no-install-recommends -y build-essential software-properties-common && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt install --no-install-recommends -y python3.8 python3-pip python3-setuptools python3-distutils && \
    apt clean && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3 /usr/bin/python
RUN python -m pip install --upgrade pip

ADD alpaca.py /
ADD common.py /
ADD models /models
ADD requirements.txt /

RUN apt-get -y update && apt-get -y upgrade && apt-get install -y ffmpeg && apt-get -y install git
RUN pip install torch==2.0.0+cu117 torchvision==0.15.1+cu117 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu117
RUN pip install -r requirements.txt

#RUN python -c "from transformers import pipeline; pipeline('text-generation', model='akoksal/LongForm-OPT-2.7B')"
#RUN python -c "import whisper; whisper.load_model('small')"
#RUN python -c "from transformers import pipeline; pipeline('text-generation', model='declare-lab/flan-alpaca-base')"
#RUN python -c "from transformers import pipeline; pipeline('text-generation', model='akoksal/LongForm-OPT-2.7B')"

CMD [ "python", "./alpaca.py" ]