FROM docker.texttechnologylab.org/vasili/python-cuda:0.1

ADD alpaca.py /
ADD common.py /
ADD models /models
ADD requirements.txt /

RUN pip install torch==2.0.0+cu117 torchvision==0.15.1+cu117 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu117
RUN pip install -r requirements.txt

#RUN python -c "from transformers import pipeline; pipeline('text-generation', model='akoksal/LongForm-OPT-2.7B')"
#RUN python -c "import whisper; whisper.load_model('small')"
#RUN python -c "from transformers import pipeline; pipeline('text-generation', model='declare-lab/flan-alpaca-base')"
#RUN python -c "from transformers import pipeline; pipeline('text-generation', model='akoksal/LongForm-OPT-2.7B')"

CMD [ "python", "./alpaca.py" ]