services:
  api:
    image: docker.texttechnologylab.org/vasili/database-api:0.3
    #build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    expose:
      - "5000"
    container_name: database_api