version: '3'
services:
  host:
    image: vasili/chatbot-host
    #build: .
    environment:
      PORT: 5000
      SOCKET_SECRET: 'reallyGoodSecret!'
    ports:
      - "5000:5000"
    expose:
      - "5000"
    container_name: chatbot_host
    networks:
      - chatbot_net
  longform:
    image: vasili/chatbot-longform
    #build:
    #  context: ./chatbots/
    #  dockerfile: Dockerfile-longform
    environment:
      HOST: chatbot_host
      PORT: 5000
      LONGFORM_DEVICE: cuda:0
      LONGFORM_MODEL: akoksal/LongForm-OPT-2.7B
      LONGFORM_TOKENS: 1024
      WHISPER_MODEL: small
      LOAD_ON_START: True
    container_name: chatbot_longform
    networks:
      - chatbot_net
    depends_on:
      - "host"
  alpaca:
    image: vasili/chatbot-alpaca
    #build:
    #  context: ./chatbots/
    #  dockerfile: Dockerfile-alpaca
    environment:
      HOST: chatbot_host
      PORT: 5000
      ALPACA_MODEL: declare-lab/flan-alpaca-base
      WHISPER_MODEL: small
      LOAD_ON_START: True
    container_name: chatbot_alpaca
    networks:
      - chatbot_net
    depends_on:
      - "host"
networks:
  chatbot_net:
    internal: false
